public class JwtBodyJson {
 public String aud;
 public String iss;
 public double iat;
 public double nbf;
 public double exp;
 public String acr;
 public String aio;
 public List<String> amr;   //CRTdebug
 public String appid; 
 public String appidacr;
 public String email;
 public String family_name;
 public String given_name;
 public String idp;
 public String ipaddr;
 public String name;
 public String oid;
 public String onprem_sid;  //CRTdebug
 public String rh;
 public String scp;
 public String sub;
 public String tid;
 public String unique_name;
 public String upn;     //CRTdebug
 public String uti;
 public String ver;
}